DEP-6 -- Check branches list

diff --git a/.github/actions/dependaboja/action.yaml b/.github/actions/dependaboja/action.yaml
--- a/.github/actions/dependaboja/action.yaml
+++ b/.github/actions/dependaboja/action.yaml
@@ -10,6 +10,11 @@ inputs:
     description: Comma separated list of branches which should be merged to agregated dependency branches automatically. Default is 'master,main'
     required: false
     default: master,main
+  fetch_depth:
+    description: We need a deep fetch in order to merge
+    required: false
+    default: master,main
+
 
 outputs: {}
   # random-number:
@@ -28,3 +33,35 @@ runs:
       if: ${{ github.event_name == 'push' }}
       shell: bash
       run: echo this was a push!
+
+    - name: Is it a branch to sync?
+      id: shouldsync
+      if: ${{ github.event_name == 'push' }}
+      shell: bash
+      run: |
+        STR="${{inputs.sync_with}}"
+        readarray -d , -t ARR <<< "$STR"
+        for word in "${ARR[@]}"; do
+          echo $word
+          if [ $word == "${{github.ref_name}}" ]; then
+            echo "::set-output name=shouldsync::1"
+          fi
+        done
+
+    - name: Read dependabot config
+      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
+      shell: bash
+      run: |
+        if [ -f ./.github/dependabot.yaml ]; then
+          cat ./.github/dependabot.yaml
+        elif [ -f ./.github/dependabot.yml ]; then
+          cat ./.github/dependabot.yml
+        else
+          echo "Cannot find dependabot config"
+          exit 1
+        fi
+
+    - name: Report skip branch
+      if: ${{steps.shouldsync.outputs.shouldsync != 1}}
+      shell: bash
+      run: echo "Skip this branch"
